export const clientData = [
    {
        id: 1,
        name: 'John Doe',
        image: '/images/user1.png',
        work: 'CEO',
        review: 'The service is great and the support is top-notch. I highly recommend it! I will definitely use it again!',
    },
    {
        id: 2,
        name: 'Jane Smith',
        image: '/images/user2.png',
        work: 'Marketing Manager',
        review: 'Crown AI helped streamline our customer service operations. Our clients love the efficiency!',
    },
    {
        id: 3,
        name: 'Evel Davis',
        image: '/images/user3.png',
        work: 'Product Designer',
        review: 'Using Crown AI has transformed the way we handle customer inquiries. The automation saves us hours every week!',
    },
    {
        id: 4,
        name: 'Michael Johnson',
        image: '/images/user4.png',
        work: 'Operations Lead',
        review: "The integration was seamless, and the AI interactions are so smooth. Couldn't be happier with the results!",
    },
    {
        id: 5,
        name: 'Jeson Lee',
        image: '/images/user5.png',
        work: 'HR Manager',
        review: 'Crown AI has made our customer interactions so much easier. The automation is truly impressive!',
    },
    {
        id: 6,
        name: 'David Brown',
        image: '/images/user6.png',
        work: 'CTO',
        review: 'We were skeptical at first, but Crown AI proved to be an incredible tool for improving our response time.',
    },
    {
        id: 7,
        name: 'Sarah Wilson',
        image: '/images/user7.png',
        work: 'Customer Success Manager',
        review: "The analytics and insights we gain from Crown AI are fantastic. We're seeing a huge improvement in customer satisfaction.",
    },
    {
        id: 8,
        name: 'Chris Taylor',
        image: '/images/user8.png',
        work: 'Small Business Owner',
        review: 'This tool is a game-changer for small businesses like mine. The automated customer service has saved me so much time!',
    },
    {
        id: 9,
        name: 'James Anderson',
        image: '/images/user9.png',
        work: 'Sales Director',
        review: "Crown AI's automation has completely changed the way we do sales outreach. Our conversion rates are through the roof!",
    },
    {
        id: 10,
        name: 'Olivia Martinez',
        image: '/images/user10.png',
        work: 'Tech Entrepreneur',
        review: "I've used many AI tools, but Crown AI stands out for its ease of use and excellent customer service. Highly recommended!",
    },
];
